// Date: 30.08.2012 3:03:36
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer bone;
    ModelRenderer skull;
    ModelRenderer bone2;
    ModelRenderer chest;
    ModelRenderer bone3;
    ModelRenderer bone4;
    ModelRenderer bone5;
  
  public ModelNew()
  {
    textureWidth = 41;
    textureHeight = 33;
    
      bone = new ModelRenderer(this, 0, 14);
      bone.addBox(0F, 0F, 0F, 9, 1, 1);
      bone.setRotationPoint(-2F, 23F, -7F);
      bone.setTextureSize(41, 33);
      bone.mirror = true;
      setRotation(bone, 0F, -0.2602503F, 0F);
      skull = new ModelRenderer(this, 0, 0);
      skull.addBox(-3F, -3F, -3F, 6, 5, 6);
      skull.setRotationPoint(0F, 15F, 3F);
      skull.setTextureSize(41, 33);
      skull.mirror = true;
      setRotation(skull, -0.129712F, -0.1259942F, -0.2230717F);
      bone2 = new ModelRenderer(this, 0, 14);
      bone2.addBox(-5F, 0F, 0F, 10, 1, 1);
      bone2.setRotationPoint(0F, 23F, 6F);
      bone2.setTextureSize(41, 33);
      bone2.mirror = true;
      setRotation(bone2, 0F, 0.0743572F, 0F);
      chest = new ModelRenderer(this, 0, 16);
      chest.addBox(-4F, -4F, 0F, 7, 9, 3);
      chest.setRotationPoint(0.8666667F, 19F, 0.6666667F);
      chest.setTextureSize(41, 33);
      chest.mirror = true;
      setRotation(chest, 0F, 0F, 0F);
      bone3 = new ModelRenderer(this, 27, 0);
      bone3.addBox(0F, -6F, 0F, 1, 9, 1);
      bone3.setRotationPoint(6F, 24F, 4F);
      bone3.setTextureSize(41, 33);
      bone3.mirror = true;
      setRotation(bone3, 1.570796F, 0.2602503F, 0F);
      bone4 = new ModelRenderer(this, 0, 14);
      bone4.addBox(-6F, 0F, 0F, 9, 1, 1);
      bone4.setRotationPoint(-6.6F, 23.26667F, -3.666667F);
      bone4.setTextureSize(41, 33);
      bone4.mirror = true;
      setRotation(bone4, 1.282662F, 1.375609F, 0.1115358F);
      bone5 = new ModelRenderer(this, 27, 0);
      bone5.addBox(0F, 0F, 0F, 1, 6, 1);
      bone5.setRotationPoint(-4.666667F, 18F, 4.866667F);
      bone5.setTextureSize(41, 33);
      bone5.mirror = true;
      setRotation(bone5, -0.2974289F, 0.3717861F, 0.2230717F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bone.render(f5);
    skull.render(f5);
    bone2.render(f5);
    chest.render(f5);
    bone3.render(f5);
    bone4.render(f5);
    bone5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
